#!/bin/sh

cd "${0%/*}" || exit 1
libBloom=$(cd ../../fasguardlib-filter && pwd) || exit 1
exec bjam \
    include="${libBloom}"/include \
    search="${libBloom}"/src \
    dll-path="${libBloom}"/src \
    || exit 1
